[
  'stopped',
  'disconnected',
  'connected',
  'programRunning',
  'programFinished',
  'programStopped',
  'programErrored',
  'remote/stopped',
  'remote/disconnected',
  'remote/connected',
  'remote/programRunning',
  'remote/programFinished',
  'remote/programStopped',
  'remote/programErrored'
].forEach(function(stateName)
{
  exports[stateName] = require('./' + stateName);
});
